repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 'v4.0.1' # Use the revision sha / tag you want to point at
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-docstring-first
  - id: check-json
  - id: check-yaml
  - id: debug-statements
  - id: name-tests-test
    args: ['--django']
    exclude: []
  - id: requirements-txt-fixer

- repo: https://github.com/psf/black
  rev: '21.12b0' # Use the revision sha / tag you want to point at
  hooks:
  - id: black
    args: ["--line-length", "80"]

- repo: https://github.com/pre-commit/mirrors-isort
  rev: 'v5.9.3' # Use the revision sha / tag you want to point at
  hooks:
  - id: isort
    args: ["--profile", "black"]

- repo: https://github.com/myint/docformatter
  rev: v1.3.1
  hooks:
    - id: docformatter
      args: ["--in-place"]

- repo: https://github.com/pycqa/pydocstyle
  rev: 6.1.1
  hooks:
  - id: pydocstyle
    args:
    - --convention=numpy
    # This is provided for smooth migration, should be removed eventually
    # List of all rules: http://www.pydocstyle.org/en/stable/error_codes.html
    # D105: temporarily ignored, all our magic methods are very simple
    - --add-ignore=D105

- repo: https://gitlab.com/pycqa/flake8
  rev: '3.9.2'
  hooks:
  - id: flake8
    args:
    # This is provided for smooth migration, should be removed eventually
    # List of all rules: https://lintlyci.github.io/Flake8Rules/
    # F401: temporarily ignored, we have too many of these
    # F841: temporarily ignored, we have too many of these
    # E402: temporarily ignored for code using sys.path.append() for imports
    # E731: temporarily ignored, we love functional programming
    # E741: temporarily ignored, we all use good font
    - --ignore=F401,F841,E402,E731,E741

- repo: https://github.com/PyCQA/pylint
  rev: 'v2.12.2' # Use the revision sha / tag you want to point at
  hooks:
  - id: pylint
    args: ["--disable", "C,R,W"]
